sonar.projectKey=Concord-API_API5-Pipeline
sonar.organization=concord-api
sonar.sources=pipeline
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results/pytest.xml
